server:
    port: 8762

eureka:
    instance:
        appname: dashboard
        instanceId: dashboard:${spring.application.instance_id:${random.value}}
        metadataMap:
            instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        enabled: true
        healthcheck:
            enabled: true
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://admin:admin@localhost:8761/eureka/
